from turtle import *
t = Turtle()
t.speed(4)

unit_size = 20
t.left(90)

def ieee(a):
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.left(90)
    t.forward(3*a)
    t.left(90)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(2.5*a)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.left(90)
    t.forward(3*a)
    t.left(90)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(2.5*a)
    t.penup()
    t.right(180)

    for i in range(3):
            if (i > 0):
                t.forward(2*a)
            else:
                t.forward(3*a)
            t.pendown()
            t.forward(1.5 * a)
            t.left(90)
            t.forward(a)
            t.left(90)
            t.forward(a)
            t.right(90)
            t.forward(a)
            t.right(90)
            t.forward(a)
            t.left(90)
            t.forward(a)
            t.left(90)
            t.forward(a)
            t.right(90)
            t.forward(a)
            t.right(90)
            t.forward(a)
            t.left(90)
            t.forward(a)
            t.left(90)
            t.forward(1.5 * a)
            t.left(90)
            t.forward(5 * a)
            t.penup()
            t.left(90)

def turtle(a):
     t.forward(a)
     t.right(45)
     t.forward(a)
     t.right(45)
     t.forward(2*a)
     t.right(45)
     t.forward(a)
     t.right(45)
     t.forward(a)
     t.right(90)
     t.forward(4.5*a)
     t.right(45)
     t.forward(a)
     t.right(45)
     t.forward(a)
     t.right(30)
     t.forward(0.25*a)
     t.right(60)
     t.forward(0.25*a)
     t.right(60)
     t.forward(0.25*a)
     t.right(30)
     t.forward(a*.1)
     t.right(90)
     t.forward(0.7*a)
     t.right(45)
     t.forward(0.25*a)
     t.backward(0.25*a) 
     t.left(45)
     t.backward(0.9*a)
     t.left(45)
     t.backward(0.25*a) 
     t.forward(0.25*a) 
     t.right(45)
     t.forward(0.25*a) 
     t.left(90)
     t.forward(0.75*a) 
     t.left(45)
     t.forward(0.7*a)
     t.left(45)
     t.forward(0.85*a)  
     t.right(90)
     t.forward(a)
     t.left(90)
     t.forward(.25*a)
     t.left(90)
     t.forward(.65*a)
     t.right(90)
     t.forward(3*a)
     t.right(90)
     t.forward(.65*a)
     t.right(90)
     t.forward(.25*a)
     t.right(90)
     t.forward(.65*a)

     
     
     
     

turtle(40)

t.screen.mainloop()